### ISSUE TITLE
Bug with channel 4

### ISSUE THREAD

**Issue by realTobby** [ThKattanek/mod-player#1]
Example mod: attached
[pokemon_gym.zip](https://github.com/ThKattanek/mod-player/files/2402565/pokemon_gym.zip)

**Comment by ThKattanek** [comment]
ok i fix this problem ;)

**Comment by ThKattanek** [comment]
this bug is fixed. add effect command 0xEC.
--> https://github.com/ThKattanek/mod-player/commit/925f634ed36f5155787c759984193af3ead6e16d
